language: scala
jdk: oraclejdk8
script: ./.travis.sh
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
before_install:
  - git fetch --tags
sudo: required
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
  - name: update-website
    if: (branch = master AND type = push) OR (tag IS present)
  - name: upload-launcher # TODO Run before previous one once this works fine
    if: tag IS present
jobs:
  include:
  - env: VALIDATE_EXAMPLES=1 # unused from the script, just to know what the job does from the Travis UI
    addons:
      apt:
        sources:
          - deadsnakes
        packages:
          - python3.6
    install:
      - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
      - python3.6 -V
      - pip3 -V
      - sudo pip3 install -r examples/requirements.txt
    script: scripts/setup-and-validate-examples.sh
  - scala: 2.11.12
  - scala: 2.12.6
  - scala: 2.12.7
  - scala: 2.12.8
  - scala: 2.12.8
    jdk: openjdk11
  - name: "Website"
    script: scripts/update-website.sh
  - stage: release
    script: sbt ci-release
  - stage: update-website
    env: PUSH_WEBSITE=1
    script: scripts/update-website.sh
  - stage: upload-launcher
    name: "Upload launcher"
    script: scripts/upload-launcher.sh
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
