language: scala
jdk: oraclejdk8
script: ./.travis.sh
cache:
  directories:
  - $HOME/.cache
  - $HOME/.ivy2/cache
  - $HOME/.sbt
git:
  depth: false
before_install:
  - source scripts/website/setup-build-tools.sh
sudo: required
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
  - name: upload-launcher
    if: tag IS present
  - name: update-versioned-docs
    if: tag IS present
  - name: update-website
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - env: VALIDATE_EXAMPLES=1 # unused from the script, just to know what the job does from the Travis UI
    addons:
      apt:
        sources:
          - deadsnakes
        packages:
          - python3.6
    install:
      - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
      - python3.6 -V
      - pip3 -V
      - sudo pip3 install -r examples/requirements.txt
    script: scripts/setup-and-validate-examples.sh
  - scala: 2.11.12
  - scala: 2.12.6
  - scala: 2.12.7
  - scala: 2.12.8
  - scala: 2.12.8
    jdk: openjdk11
  - name: "Website"
    script: amm scripts/site.sc --publishLocal true
  - stage: release
    script: sbt ci-release
  - stage: upload-launcher
    name: "Upload launcher"
    script: scripts/upload-launcher.sh
  - stage: update-versioned-docs
    env: WEBSITE_DIR=docs/website VERSIONED_DOCS_REPO=almond-sh/versioned-docs
    script:
      - amm scripts/site.sc --publishLocal true --npmInstall true --yarnRunBuild true
      - scripts/website/versioned-docs.sh --update
  - stage: update-website
    env: WEBSITE_DIR=docs/website REPO=almond-sh/almond VERSIONED_DOCS_REPO=almond-sh/versioned-docs
    name: "Push website"
    script:
      - scripts/website/versioned-docs.sh
      - amm scripts/site.sc --publishLocal true --npmInstall true --yarnRunBuild true --relativize true
      - scripts/website/push-website.sh
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
